### PR TITLE
Show partitions count on subscription stats page

### PR DESCRIPTION
**Pull request by a1exsh**
Sometimes it's helpful to have a quick way to check it.

### CODE REVIEW

**Comment by a1exsh** [comment]
Looks like this:
image

**Comment by a1exsh** [comment]
:+1:

**Comment by adyach** [comment]
👍

**Comment by a1exsh** [comment]
Ah, just noticed there is a helper function to avoid the "(s)" for maybe plural.  Will try to use that one.

**Comment by a1exsh** [comment]
Ah, just noticed there is a helper function to avoid the "(s)" for maybe plural.  Will try to use that one.

**Comment by a1exsh** [comment]
image

**Comment by Jan-M** [comment]
:+1:

**Comment by a1exsh** [comment]
:+1:

**Pull request merged**
