### PR TITLE
Change default owning application for event type, query create to an empty value

### PR DESCRIPTION
**Pull request by antban**
There is no meaning in having default value that users have to constantly override.

### CODE REVIEW

**Comment by a1exsh** [comment]
What about subscriptions?  They are rarely created manually I guess, but I see no reason to keep it there either.

**Comment by antban** [comment]
:+1:

**Comment by a1exsh** [comment]
Unsuprisingly, the tests expect these fields to be set:

``
Failures:
1) Create Event type form should submit default data (happy scenario)
  Message:
    Failed: element not interactable
  Stack:
    Error: An element command could not be completed because the element is not visible on the page.
        at elementIdClick("0.21471385270509247-4") - click.js:20:22
2) Create Subscription form should submit default data (happy scenario)
  Message:
    Expected false to be truthy 'Submit btn should be enabled if name is set'.
...
```

**Comment by antban** [comment]
Who-ho! The tests are passing!

**Comment by antban** [comment]
:+1:

**Comment by a1exsh** [comment]
:+1:

**Pull request merged**
