### PR TITLE
Fix typo in Subscription details

### PR DESCRIPTION
**Pull request by i-am-the-slime**
This has been annoying me for quite some time.

### CODE REVIEW

**Comment by lmontrieux** [comment]
Thank you for your PR, @i-am-the-slime . And sorry about the typo :)

**Comment by lmontrieux** [comment]
👍

**Comment by i-am-the-slime** [comment]
👍

**Comment by ferbncode** [comment]
:+1:

**Comment by lmontrieux** [comment]
👍

**Pull request merged**
